export const AVAILABLE_CITY = [
  {
    id: '5f2a4210ecdb5a5d67f0bbbc',
    name: 'bangalore',
    icon: 'bangalore.svg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: [
      'Near Me',
      'HSR Layout',
      'Whitefield',
      'Koramangala',
      'Indiranagar',
      'MG Road',
      'Electronic City',
      'Bannerghatta Road',
      'Kalyan Nagar',
      'Manyata Tech Park',
      'Rajajinagar',
      'JP Nagar',
      'Sanjay Nagar',
      'Bellandur',
      'Marathahalli',
      'Banashankari',
      'Malleshwaram',
      'Hebbal',
      'BTM Layout',
      'Sadashivanagar',
      'Outer Ring Road',
      'Residency Road',
      'Sarjapur Road',
      'Domlur',
      'Hosur Road',
      'KR Puram',
      'Kadubeesanahalli',
    ],
  },
  {
    id: '5e3eb83c18c88277e81427d9',
    name: 'gurugram',
    icon: 'gurugram.svg',
    image: '../../../assets/images/cities-img/gurugram-city-img.jpg',
    for_coWorking: true,
    for_office: true,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Udyog Vihar',
      'MG Road',
      'Cyber City',
      'Golf Course Road',
      'Golf Course Extension Road',
      'Sector 44',
      'Sohna Road',
      'DLF',
      'Sector 18',
      'Cyber Hub',
      'Unitech Cyber Park',
      'Sushant Lok',
      'Sector 57',
      'Manesar',
    ],
  },
  {
    id: '5f5b1f728bbbb85328976417',
    name: 'mumbai',
    icon: 'mumbai.svg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Andheri',
      'BKC',
      'Goregaon',
      'Malad',
      'Lower Parel',
      'Borivali',
      'Powai',
      'Vashi',
      'Mulund',
      'Navi Mumbai',
      'Andheri East',
      'Bandra',
      'Andheri West',
      'Borivali West',
      'Dadar',
      'VIkhroli',
      'Vile Parle',
      'Worli',
      'Churchgate',
      'Kurla',
      'Marol',
      'Thane',
    ],
  },
  {
    id: '5f338a5f59d5584617676837',
    name: 'hyderabad',
    icon: 'hyderabad.svg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Kondapur',
      'Hitech City',
      'Gachibowli',
      'Madhapur',
      'Jubilee Hills',
      'Banjara Hills',
      'Kukatpally',
      'Begumpet',
      'Secunderabad',
    ],
  },
  {
    id: '5e3eb83c18c88277e8142795',
    name: 'pune',
    icon: 'pune.svg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Baner',
      'Magarpatta',
      'Viman Nagar',
      'Hinjewadi',
      'Kharadi',
      'Pimpri Chinchwad',
      'Aundh',
      'Balewadi',
      'Shivaji Nagar',
      'Wakad',
      'Bavdhan',
      'Pimple Saudagar',
      'Kothrud',
      'Kalyani Nagar',
      'Hadapsar',
      'Koregaon Park',

    ],
  },
  {
    id: '5e3e77c6936bc06de1f9a2d9',
    name: 'delhi',
    icon: 'delhi.svg',
    image: '../../../assets/images/cities-img/delhi-city-img.jpg',
    for_coWorking: true,
    for_office: true,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Connaught Place',
      'South Delhi',
      'Dwarka Delhi',
      'Nehru Place',
      'Netaji Subhash Place',
      'Aerocity',
      'Janakpuri',
      'West Delhi',
      'East Delhi',
      'Rohini',
      'Saket',
      'Okhla',
      'Laxmi Nagar',
      'Green Park',
      'Hauz Khas',
      'Pitampura',
      'Rajouri Garden',
      'Vasant Kunj',
      'Central Delhi',
      'East of Kailash',
      'Greater Kailash',
      'Karol Bagh',
      'Kirti Nagar',
      'Malviya Nagar',
      'Mayur Vihar',
      'Paschim Vihar',
      'Preet Vihar',
      'South Extension',
      'Tilak Nagar',
      'Indirapuram',
      'Defence Colony',
      'Patel Nagar',
      'Lajpat Nagar',
      'Uttam Nagar',
      'Jasola',
      'Mohan Cooperative',
    ],
  },

  {
    id: '5e3e77de936bc06de1f9a5e2',
    name: 'noida',
    icon: 'noida.svg',
    image: '../../../assets/images/cities-img/noida-city-img.jpg',
    for_coWorking: true,
    for_office: true,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Sector 2',
      'Sector 62',
      'Sector 63',
      'Sector 59',
      'Sector 1',
      'Greater Noida',
      'Sector 16',
      'Noida Expressway',
      'Sector 18',
      'Sector 125',
      'Sector 127',
      'Sector 135',
      'Noida extension',
    ],
  },
  {
    name: 'indore',
    id: '5f60926926e9e64d7b61b41b',
    icon: 'indore.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: ['Near Me', 'AB Road', 'LIC Colony', 'Ratna Lok Colony', 'Ravindra Nagar', 'South Tukoganj', 'Vijay Nagar'],
  },
  {
    name: 'chennai',
    id: '5f7410348c4e6961990e5a21',
    icon: 'chennai.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: ['Near Me', 'Guindy', 'Anna Nagar', 'Adyar', 'T Nagar', 'OMR', 'Velachery', 'Nungambakkam'],
  },
  {
    name: 'ahmedabad',
    id: '5f7af1c48c4e6961990e620e',
    icon: 'ahmedabad.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: ['Near Me', 'Vastrapur', 'SG Highway', 'Navrangpura', 'Prahlad Nagar', 'Satellite', 'Ellisbridge'],
  },
  {
    name: 'kochi',
    id: '5f8d31a7c2502350f24fee9b',
    icon: 'kochi.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: ['Near Me', 'Ernakulam', 'Kadavanthra', 'Kakkanad', 'VIP Road'],
  },
  {
    name: 'chandigarh',
    id: '5f8d31c0c2502350f24fee9d',
    icon: 'chandigarh.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Mohali',
      'Zirakpur',
      'Madhya Marg',
      'Sahibzada Ajit Singh Nagar',
      'Sector-34A',
      'Sector-37',
      'Phase 8B',
      'Phase 7',
    ],
  },
  {
    name: 'jaipur',
    id: '5f8d319fc2502350f24fee9a',
    icon: 'jaipur.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: [
      'Near Me',
      'Vaishali Nagar',
      'Indarpuri',
      'Mansarovar',
      'Ganpati Nagar',
      'Lalkothi',
      'Nirman Nagar',
      'Subhash Nagar',
    ],
  },
  {
    name: 'lucknow',
    id: '5f8d31b0c2502350f24fee9c',
    icon: 'lucknow.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: ['Near Me', 'Gomti Nagar', 'Indira Nagar', 'Vibhuti Khand'],
  },
  {
    name: 'kolkata',
    id: '5f8d3541c2502350f24feeb6',
    icon: 'kolkata.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: ['Near Me', 'Salt Lake', 'Rajarhat', 'Dalhousie', 'Howrah', 'Bidhannagar', 'Bhowanipur'],
  },
  {
    name: 'coimbatore',
    id: '5f9bf559c2502350f2500152',
    icon: 'coimbatore.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: ['Near Me', 'Ramanathapuram', 'RS Puram', 'Eachanari', 'Cross Cut Road'],
  },
  {
    name: 'goa',
    id: '5f9a6a18c2502350f24ffc9e',
    icon: 'goa.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: ['Near Me', 'Margao', 'Anjuna', 'Panaji'],
  },
  {
    name: 'bhubaneswar',
    id: '5ff4367926f5cd67c919a112',
    icon: 'bhuvneshwar.jpeg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: [],
  },
  {
    id: '5fd088bb1be4d8562d3bc9be',
    name: 'faridabad',
    icon: 'faridabad.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: [],
  },

  // {
  //   name: 'dehradun',
  //   id: '5ff3fbd1a3304537cef8378a',
  //   icon: 'dehradun.jpeg',
  //   for_coWorking: false,
  //   for_office: false,
  //   for_coLiving: false,
  //   locations: [],
  // },

];

export const AVAILABLE_CITY_CO_LIVING = [
  {
    id: '5e3e77c6936bc06de1f9a2d9',
    name: 'delhi',
    icon: 'delhi.svg',
    for_coWorking: true,
    for_office: true,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Connaught Place',
      'South Delhi',
      'Dwarka',
      'Nehru Place',
      'Netaji Subhash Place',
      'Aerocity',
      'Janakpuri',
      'West Delhi',
      'East Delhi',
      'Rohini',
      'Saket',
      'Okhla',
      'Laxmi Nagar',
      'Green Park',
      'Hauz Khas',
      'Pitampura',
      'Rajouri Garden',
      'Vasant Kunj',
      'North Delhi',
      'Malviya Nagar',
      'Sarita Vihar',
      'Karol Bagh',
      'North Campus',
      'South Campus',
      'Central Delhi',
      'Satya Niketan',
      'Patel Nagar',
      'Lajpat Nagar',
      'Greater Kailash',
      'East of Kailash',
      'Uttam Nagar',
    ],
  },
  {
    id: '5e3eb83c18c88277e81427d9',
    name: 'gurugram',
    icon: 'gurugram.svg',
    for_coWorking: true,
    for_office: true,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Golf Course Road',
      'Sohna Road',
      'MG Road',
      // 'Golf Course Extension',
      // 'Huda City Center',
      'Udyog Vihar',
      'Cyber City',
      'Rajiv Chowk',
      'DLF Phase 1',
      'DLF Phase 2',
      'DLF Phase 3',
      'DLF Phase 4',
      'DLF Phase 5',
      'Sector 31',
      'Sector 69',
      'Sector 48',
      'Sector 47',
      'Sector 44',
      'Sector 45',
      'Sector 43',
      'Sector 42',
      'Sector 52',
      'Sector 53',
      'Sector 54',
      'Sector 55',
      'Sector 56',
      'Sector 58',
      'Sector 61',
      'Sector 62',
      'Sector 65',
      'Sector 66',
      'Sector 67',
      'Sector 14',
      'Sector 15',
      'Sector 17',
      'Sector 23',
      'Sector 24',
      'Sector-25',
      'Sector 28',
      'sector 33',
      'Sector 38',
      'Sector 39',
      'Sector  9',
    ],
  },
  {
    id: '5e3e77de936bc06de1f9a5e2',
    name: 'noida',
    icon: 'noida.svg',
    for_coWorking: true,
    for_office: true,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Sector 2',
      'Sector 62',
      'Sector 63',
      'Sector 59',
      'Sector 1',
      'Greater Noida',
      'Sector 16',
      'Noida Expressway',
      'Sector 18',
      'Sector 125',
      'Sector 127',
      'Sector 135',
    ],
  },
  {
    id: '5f2a4210ecdb5a5d67f0bbbc',
    name: 'bangalore',
    icon: 'bangalore.svg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Koramangala',
      'Marathahalli',
      'HSR Layout',
      'Indiranagar',
      'Whitefield',
      'Electronic City',
      'Jaya Nagar',
      'Bellandur',
      'Manyata Tech Park',
      'J P Nagar',
      'Domlur',
      'Mahadevapura',
      'Nagawara',
      'Hebbal',
      'Kadubeesanahalli',
      'Bagmane Tech Park',
      'Bommanahalli',
      'Madiwala',
      'MG Road',
      'KR Puram',
      'Murugeshpalya',
      'Kundalahalli',
      'Sarjapur',
      'Ecospace',
      'Banaswadi',
      'Bommasandra',
      'AECS Layout',
      'Wilson Garden',
      'Hoodi',
      'Doddanekundi',
      'Ejipura',
      'Green Glen layout',
      'ITPL',
      'Hope Farm',
      'Silk Board',
      'Bannerghatta road',
      'Lal Bagh',
      'Thippasandra',
      'Tavarekere',
      'Kudlu Gate',
      'HBR Layout',
      'Richmond Town',
      'Varthur',
      'Dairy Circle',
      'Hennur Road',
      'Brookfield',
      'Munnekolala',
      'Thanisandra',
      'Christ college',
      'Central Mall',
      'Shantiniketan',
      'HAL Road',
      'Mysore Road',
    ],
  },
  {
    id: '5f338a5f59d5584617676837',
    name: 'hyderabad',
    icon: 'hyderabad.svg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Gachibowli',
      'Kondapur',
      'Miyapur',
      'Hitech City',
      'Madhapur',
      'KPHB',
      'Hafeezpet',
      'Banjara Hills',
      'Jubilee Hills',
      'Begumpet',
      'Kukatpally',
      'Ameerpet',
      'Mehdipatnam',
      'Kothaguda',
      'Nizampet',
      'Narsingi',
    ],
  },

  {
    id: '5f5b1f728bbbb85328976417',
    name: 'mumbai',
    icon: 'mumbai.svg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Thane',
      'Navi Mumbai',
      'Andheri',
      'Andheri East',
      'Lower Parel',
      'Borivali',
      'Bandra',
      'Mulund',
      'Vashi',
      'Goregaon',
      'Malad',
      'Powai',
      'Andheri West',
      'BKC',
      'Borivali West',
      'Dadar',
      'VIkhroli',
      'Vile Parle',
      'Worli',
      'Churchgate',
      'Kurla',
      'Marol',
    ],
  },
  {
    id: '5e3eb83c18c88277e8142795',
    name: 'pune',
    icon: 'pune.svg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: [
      'Near Me',
      'Baner',
      'Aundh',
      'Kharadi',
      'Viman Nagar',
      'Wakad',
      'Hinjewadi',
      'Bavdhan',
      'Pimple Saudagar',
      'Kothrud',
      'Kalyani Nagar',
      'Magarpatta',
      'Hadapsar',
      'Koregaon Park',
      'Pimpri Chinchwad',
    ],
  },
  {
    name: 'indore',
    id: '5f60926926e9e64d7b61b41b',
    icon: 'indore.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: ['AB Road', 'LIC Colony', 'Ratna Lok Colony', 'Ravindra Nagar', 'South Tukoganj', 'Vijay Nagar'],
  },

  {
    name: 'chennai',
    id: '5f7410348c4e6961990e5a21',
    icon: 'chennai.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: ['Guindy', 'Anna Nagar', 'OMR', 'Nungambakkam', 'Adyar', 'T Nagar', 'Velachery'],
  },
  {
    name: 'ahmedabad',
    id: '5f7af1c48c4e6961990e620e',
    icon: 'ahmedabad.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    locations: [
      'Near Me',
      'SG Highway',
      'Navrangpura',
      'Vastrapur',
      'Prahlad Nagar',
      'Satellite',
      'Ellisbridge',
      'Gota',
      'Odhav',
      'Chandkheda',
      'Gurukul Road',
      'Ghatlodia',
      'Thaltej',
      'Vejalpur',
      'Bodakdev',
      'Maninagar',
      'Makarba',
      'Vishala',
      'Naranpura',
      'Shantipura',
      'Ambawadi',
      'Memnagar',
      'Motera',
      'Paldi',
      'Usmanpura',
      'Sanand',
      'Girdhar Nagar',
      'Madhupura',
      'Dariyapur',
      'Vasna',
      'Bopal',
    ],
  },
  {
    name: 'kochi',
    id: '5f8d31a7c2502350f24fee9b',
    icon: 'kochi.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: [
      'Palarivattom',
      'Edappally',
      'kakkanad',
      'Maradu',
      'Elamakkara',
      'Vazhakkala',
      'Kadavanthra',
      'Kaloor',
      'Thevara',
      'Thomaspuram',
      'Padamughal',
      'Kalamassery',
      'Aluva',
      'Tripunithura',
      'Irimpanam',
    ],
  },
  {
    name: 'chandigarh',
    id: '5f8d31c0c2502350f24fee9d',
    icon: 'chandigarh.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: [
      'Zirakpur',
      'Sector-43',
      'Sector-22',
      'Sector-37',
      'Madhya Marg',
      'Sector-15',
      'Sector-16',
      'Sector-34',
      'sector-40B',
      'Kharar',
      'Kurali',
      'Mohali',
      'Sahibzada Ajit Singh Nagar',
      'Sector-38',
      'Sector-21',
      'Nayagaon',
      'DLF Mullanpur',
      'New Chandigarh',
      'Phase 8B',
    ],
  },
  {
    name: 'jaipur',
    id: '5f8d319fc2502350f24fee9a',
    icon: 'jaipur.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: [
      'Vaishali Nagar',
      'Indarpuri',
      'Mansarovar',
      'Ganpati Nagar',
      'Lalkothi',
      'Nirman Nagar',
      'Subhash Nagar',
    ],
  },
  {
    name: 'lucknow',
    id: '5f8d31b0c2502350f24fee9c',
    icon: 'lucknow.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: [
      'Mahanagar',
      'Butler colony',
      'Gomti Nagar',
      'Vibhuti Khand',
      'Matiyari',
      'Kamta',
      'Aminabad',
      'Singar Nagar',
      'Malhaur',
      'Alambagh',
      'LDA Colony',
      'Hazratganj',
    ],
  },
  {
    name: 'kolkata',
    id: '5f8d3541c2502350f24feeb6',
    icon: 'kolkata.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: [
      'Salt Lake',
      'Rajarhat',
      'Dalhousie',
      'Howrah',
      'Bidhannagar',
      'Bhowanipur',
      'Gariahat',
      'Jadavpur',
      'Mukundapur',
      'Purba Putiary',
      'Behala',
      'Keshtopur',
      'Maniktala',
      'Sodepur',
      'Madhyamgram',
    ],
  },
  {
    name: 'coimbatore',
    id: '5f9bf559c2502350f2500152',
    icon: 'coimbatore.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: [
      'Saravanampatti',
      'Udayampalayam',
      'Peelamedu',
      'Thirumalayampalayam',
      'Kaliyapuram',
      'Kuniyamuthur',
      'Eachanari',
      'Thudiyalur',
      'Avinashi Road',
      'Gandhipuram',
      'Sidhapudur',
      'Vadavalli',
      'Kovaipudur',
      'Chinniampalayam',
      'cheran ma nagar',
      'Selvapuram',
      'Kalapatti',
      'Sowripalayam',
    ],
  },
  // {
  //   name: 'dehradun',
  //   id: '5ff3fbd1a3304537cef8378a',
  //   icon: 'dehradun.jpeg',
  //   for_coWorking: true,
  //   for_office: false,
  //   for_coLiving: true,
  //   locations: [
  //     'Pondha',
  //     'Prem Nagar',
  //     'Mitthi Behri',
  //     'Bidholi',
  //     'Kharakhet',
  //     'Ajabpur Kalan',
  //     'Balliwala',
  //     'Dalanwala',
  //     'Govind Vihar',
  //     'Kaonli',
  //     'Chukkuwala',
  //     'Clement town',
  //     'Jakhan',
  //     'Sewla Kalan',
  //     'Sahastradhara Road',
  //     'Malsi',
  //     'Aamwala',
  //     'Kanwali',
  //   ],
  // },
  {
    name: 'bhubaneswar',
    id: '5ff4367926f5cd67c919a112',
    icon: 'bhuvneshwar.jpeg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: [
      'Patia',
      'Sailashree Vihar',
      'Chandrasekharpur',
      'BJB Nagar',
      'Madanpur',
      'Khandagiri',
      'Maitri Vihar Road',
      'Nayapalli',
      'Jagamara',
      'Jayadev Vihar',
      'Brahmeswarpatna',
      'Old town',
    ],
  },

  // {
  //   name: 'Amritsar',
  //   id: '5ff315b5a3304537cef836cd',
  //   icon: 'coimbatore.png',
  //   for_coWorking: false,
  //   for_office: false,
  //   for_coLiving: false,
  //   locations: [],
  // },
  // {
  //   name: 'Kota',
  //   id: '5ff315b5a3304537cef836cd',
  //   icon: 'coimbatore.png',
  //   for_coWorking: false,
  //   for_office: false,
  //   for_coLiving: false,
  //   locations: [],
  // },
  {
    name: 'goa',
    id: '5f9a6a18c2502350f24ffc9e',
    icon: 'coimbatore.png',
    for_coWorking: true,
    for_office: false,
    for_coLiving: false,
    locations: [
      'Panjim',
      'Mapusa',
      'Durgabhat',
      'Salcete',
      'Candolim',
      'Ponda',
      'Anjuna',
      'Panaji',
      'verla parra',
      'Borim',
      'Margao',
      'Porvorim',
    ],
  },

  // {
  //   name: 'visakhapatnam',
  //   id: '5ff42164a3304537cef838ee',
  //   icon: 'coimbatore.png',
  //   for_coWorking: false,
  //   for_office: false,
  //   for_coLiving: false,
  //   locations: [],
  // },
];

export const AVAILABLE_CITY_VIRTUAL_OFFICE = [
  {
    name: 'gurugram',
    id: '5e3eb83c18c88277e81427d9',
    icon: 'gurugram.svg',
    image: 'https://cofynd-staging.s3.ap-south-1.amazonaws.com/images/original/7f11c58e38c7fe343f6dfb301f36c8a428fb954b.jpg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    for_virtualOffice: true,
    locations: [],
  },
  {
    id: '5e3e77c6936bc06de1f9a2d9',
    name: 'delhi',
    icon: 'delhi.svg',
    image: 'https://cofynd-staging.s3.ap-south-1.amazonaws.com/images/original/b6d83bfaedd8d50af65d5e4c6289e0000d9d7fc7.jpg',
    for_coWorking: true,
    for_office: true,
    for_coLiving: true,
    for_virtualOffice: true,
    locations: [],
  },
  {
    id: '5e3e77de936bc06de1f9a5e2',
    name: 'noida',
    icon: 'noida.svg',
    image: 'https://cofynd-staging.s3.ap-south-1.amazonaws.com/images/original/c5d0e008c819dcbcae8319835f7e57bdd5de8ea9.jpg',
    for_coWorking: true,
    for_office: true,
    for_coLiving: true,
    for_virtualOffice: true,
    locations: [],
  },
  {
    id: '5f2a4210ecdb5a5d67f0bbbc',
    name: 'bangalore',
    icon: 'bangalore.svg',
    image: 'https://cofynd-staging.s3.ap-south-1.amazonaws.com/images/original/117ec383b617f0622db6c54679da80c0105487f7.jpg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    for_virtualOffice: true,
    locations: [],
  },
  {
    id: '5f338a5f59d5584617676837',
    name: 'hyderabad',
    icon: 'hyderabad.svg',
    image: 'https://cofynd-staging.s3.ap-south-1.amazonaws.com/images/original/eb4aa50652a34bb24ba16368fff7f37ead469994.jpg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    for_virtualOffice: true,
    locations: [],
  },
  {
    id: '5e3eb83c18c88277e8142795',
    name: 'pune',
    icon: 'pune.svg',
    image: 'https://cofynd-staging.s3.ap-south-1.amazonaws.com/images/original/1c8435872fdbb6376c7005be8a01983980c1d709.jpg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    for_virtualOffice: true,
    locations: [],
  },
  {
    id: '5f5b1f728bbbb85328976417',
    name: 'mumbai',
    icon: 'mumbai.svg',
    image: 'https://cofynd-staging.s3.ap-south-1.amazonaws.com/images/original/6e515577a1d506a17c07be4299105476c88a7287.jpg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    for_virtualOffice: true,
    locations: [],
  },
  {
    name: 'indore',
    id: '5f60926926e9e64d7b61b41b',
    icon: 'indore.png',
    image: 'https://cofynd-staging.s3.ap-south-1.amazonaws.com/images/original/dc5ce0f99f9d9f60dbd918cb8fcbbbf55c751802.jpg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    for_virtualOffice: true,
    locations: [],
  },
  {
    name: 'ahmedabad',
    id: '5f7af1c48c4e6961990e620e',
    icon: 'ahmedabad.png',
    image: 'https://cofynd-staging.s3.ap-south-1.amazonaws.com/images/original/770e4040ababe9283a46421cc6b7a127872b9a6b.jpg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    for_virtualOffice: true,
    locations: [],
  },
  {
    name: 'kochi',
    id: '5f8d31a7c2502350f24fee9b',
    icon: 'kochi.png',
    image: 'https://cofynd-staging.s3.ap-south-1.amazonaws.com/images/original/823b4ae8fa08975d961138f1a86a3232034b3a27.jpg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    for_virtualOffice: true,
    locations: [],
  },
  {
    name: 'chennai',
    id: '5f7410348c4e6961990e5a21',
    icon: 'chennai.png',
    image: 'https://cofynd-staging.s3.ap-south-1.amazonaws.com/images/original/18f6b59cb5f91d0ae4eb3598de16f9ecdc44b996.jpg',
    for_coWorking: true,
    for_office: false,
    for_coLiving: true,
    for_virtualOffice: true,
    locations: [],
  },
];