export const GoStops_Centers = [
  {
    id: '',
    name: 'goSTOPS Bir',
    website_Url: '',
    location: ' P.O. BIR, Himachal Pradesh',
    price_type: 'week',
    starting_price: '4,199',
    show_price: '4,199',
    slug: 'gostops-bir',
    images: [
      { image: 'http://alexandro.in/gostops/bir/1.jpg' },
      { image: 'http://alexandro.in/gostops/bir/2.jpg' },
      { image: 'http://alexandro.in/gostops/bir/3.jpg' },
      { image: 'http://alexandro.in/gostops/bir/4.jpg' },
      { image: 'http://alexandro.in/gostops/bir/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Rishikesh',
    website_Url: '',
    location: ' Badrinath Rd, Tapovan, Rishikesh',
    price_type: 'week',
    starting_price: '2,599',
    show_price: '2,599',
    slug: 'gostops-rishikesh',
    images: [
      { image: 'http://alexandro.in/gostops/rishikesh/1.jpg' },
      { image: 'http://alexandro.in/gostops/rishikesh/2.jpg' },
      { image: 'http://alexandro.in/gostops/rishikesh/3.jpg' },
      { image: 'http://alexandro.in/gostops/rishikesh/4.jpg' },
      { image: 'http://alexandro.in/gostops/rishikesh/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Udaipur',
    website_Url: '',
    location: ' Pichola, Udaipur, Rajasthan',
    price_type: 'week',
    starting_price: '1,999',
    show_price: '1,999',
    slug: 'gostops-udaipur',
    images: [
      { image: 'http://alexandro.in/gostops/udaipur/1.jpg' },
      { image: 'http://alexandro.in/gostops/udaipur/2.jpg' },
      { image: 'http://alexandro.in/gostops/udaipur/3.jpg' },
      { image: 'http://alexandro.in/gostops/udaipur/4.jpg' },
      { image: 'http://alexandro.in/gostops/udaipur/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS McLeodGanj',
    website_Url: '',
    location: ' Mcleodganj Dharamshala, Himachal Pradesh',
    price_type: 'week',
    starting_price: '2,999',
    show_price: '2,999',
    slug: 'gostops-mcleodganj',
    images: [
      { image: 'http://alexandro.in/gostops/mcleodganj/1.jpg' },
      { image: 'http://alexandro.in/gostops/mcleodganj/2.jpg' },
      { image: 'http://alexandro.in/gostops/mcleodganj/3.jpg' },
      { image: 'http://alexandro.in/gostops/mcleodganj/4.jpg' },
      { image: 'http://alexandro.in/gostops/mcleodganj/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Kochi',
    website_Url: '',
    location: ' Calvathy Rd, Kochi',
    price_type: 'week',
    starting_price: '2,299',
    show_price: '2,299',
    slug: 'gostops-kochi',
    images: [
      { image: 'http://alexandro.in/gostops/kochi/1.jpg' },
      { image: 'http://alexandro.in/gostops/kochi/2.jpg' },
      { image: 'http://alexandro.in/gostops/kochi/3.jpg' },
      { image: 'http://alexandro.in/gostops/kochi/4.jpg' },
      { image: 'http://alexandro.in/gostops/kochi/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Manali',
    website_Url: '',
    location: ' Near Oak Land House, Old Manali',
    price_type: 'week',
    starting_price: '3,599',
    show_price: '3,599',
    slug: 'gostops-manali',
    images: [
      { image: 'http://alexandro.in/gostops/manali/1.jpg' },
      { image: 'http://alexandro.in/gostops/manali/2.jpg' },
      { image: 'http://alexandro.in/gostops/manali/3.jpg' },
      { image: 'http://alexandro.in/gostops/manali/4.jpg' },
      { image: 'http://alexandro.in/gostops/manali/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Jaipur',
    website_Url: '',
    location: ' Prithviraj Rd, Devi Niketan Compound, Jaipur',
    price_type: 'week',
    starting_price: '1,999',
    show_price: '1,999',
    slug: 'gostops-jaipur',
    images: [
      { image: 'http://alexandro.in/gostops/jaipur/1.jpg' },
      { image: 'http://alexandro.in/gostops/jaipur/2.jpg' },
      { image: 'http://alexandro.in/gostops/jaipur/3.jpg' },
      { image: 'http://alexandro.in/gostops/jaipur/4.jpg' },
      { image: 'http://alexandro.in/gostops/jaipur/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Mumbai',
    website_Url: '',
    location: " P D'Mello Rd, Masjid Bandar, Mumbai",
    price_type: 'week',
    starting_price: '2,399',
    show_price: '2,399',
    slug: 'gostops-mumbai',
    images: [
      { image: 'http://alexandro.in/gostops/mumbai/1.jpg' },
      { image: 'http://alexandro.in/gostops/mumbai/2.jpg' },
      { image: 'http://alexandro.in/gostops/mumbai/3.jpg' },
      { image: 'http://alexandro.in/gostops/mumbai/4.jpg' },
      { image: 'http://alexandro.in/gostops/mumbai/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Varanasi',
    website_Url: '',
    location: ' Vijaya Nagaram Colony, Bhelupur, Varanasi',
    price_type: 'week',
    starting_price: '2,599',
    show_price: '2,599',
    slug: 'gostops-varanasi',
    images: [
      { image: 'http://alexandro.in/gostops/varanasi/1.jpg' },
      { image: 'http://alexandro.in/gostops/varanasi/2.jpg' },
      { image: 'http://alexandro.in/gostops/varanasi/3.jpg' },
      { image: 'http://alexandro.in/gostops/varanasi/4.jpg' },
      { image: 'http://alexandro.in/gostops/varanasi/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Amritsar',
    website_Url: '',
    location: ' Chatiwind Gate Roundabout, Amritsar',
    price_type: 'week',
    starting_price: '2,599',
    show_price: '2,599',
    slug: 'gostops-amritsar',
    images: [
      { image: 'http://alexandro.in/gostops/amritsar/1.jpg' },
      { image: 'http://alexandro.in/gostops/amritsar/2.jpg' },
      { image: 'http://alexandro.in/gostops/amritsar/3.jpg' },
      { image: 'http://alexandro.in/gostops/amritsar/4.jpg' },
      { image: 'http://alexandro.in/gostops/amritsar/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Alleppey',
    website_Url: '',
    location: ' Cullen Rd, Alappuzha, Kerala',
    price_type: 'week',
    starting_price: '2,199',
    show_price: '2,199',
    slug: 'gostops-alleppey',
    images: [
      { image: 'http://alexandro.in/gostops/alleppey/1.jpg' },
      { image: 'http://alexandro.in/gostops/alleppey/2.jpg' },
      { image: 'http://alexandro.in/gostops/alleppey/3.jpg' },
      { image: 'http://alexandro.in/gostops/alleppey/4.jpg' },
      { image: 'http://alexandro.in/gostops/alleppey/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Munnar',
    website_Url: '',
    location: ' Anachal Rd, Munnar, Kerala',
    price_type: 'week',
    starting_price: '2,599',
    show_price: '2,599',
    slug: 'gostops-munnar',
    images: [
      { image: 'http://alexandro.in/gostops/munnar/1.jpg' },
      { image: 'http://alexandro.in/gostops/munnar/2.jpg' },
      { image: 'http://alexandro.in/gostops/munnar/3.jpg' },
      { image: 'http://alexandro.in/gostops/munnar/4.jpg' },
      { image: 'http://alexandro.in/gostops/munnar/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Palampur',
    website_Url: '',
    location: ' Bundla, Palampur, Himachal Pradesh',
    price_type: 'week',
    starting_price: '2,599',
    show_price: '2,599',
    slug: 'gostops-palampur',
    images: [
      { image: 'http://alexandro.in/gostops/palampur/1.jpg' },
      { image: 'http://alexandro.in/gostops/palampur/2.jpg' },
      { image: 'http://alexandro.in/gostops/palampur/3.jpg' },
      { image: 'http://alexandro.in/gostops/palampur/4.jpg' },
      { image: 'http://alexandro.in/gostops/palampur/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Dalhousie',
    website_Url: '',
    location: ' Karelnu Village, Dalhousie, Himachal Pradesh',
    price_type: 'week',
    starting_price: '2,599',
    show_price: '2,599',
    slug: 'gostops-dalhousie',
    images: [
      { image: 'http://alexandro.in/gostops/dalhousie/1.jpg' },
      { image: 'http://alexandro.in/gostops/dalhousie/2.jpg' },
      { image: 'http://alexandro.in/gostops/dalhousie/3.jpg' },
      { image: 'http://alexandro.in/gostops/dalhousie/4.jpg' },
      { image: 'http://alexandro.in/gostops/dalhousie/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Leh',
    website_Url: '',
    location: ' KHASARA NO. 3107, CHUBI, Leh',
    price_type: 'week',
    starting_price: '3,199',
    show_price: '3,199',
    slug: 'gostops-leh',
    images: [
      { image: 'http://alexandro.in/gostops/leh/1.jpg' },
      { image: 'http://alexandro.in/gostops/leh/2.jpg' },
      { image: 'http://alexandro.in/gostops/leh/3.jpg' },
      { image: 'http://alexandro.in/gostops/leh/4.jpg' },
      { image: 'http://alexandro.in/gostops/leh/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Mussoorie',
    website_Url: '',
    location: ' Library Road, Mussoorie, Uttarakhand',
    price_type: 'week',
    starting_price: '3,199',
    show_price: '3,199',
    slug: 'gostops-mussoorie',
    images: [
      { image: 'http://alexandro.in/gostops/mussoorie/1.jpg' },
      { image: 'http://alexandro.in/gostops/mussoorie/2.jpg' },
      { image: 'http://alexandro.in/gostops/mussoorie/3.jpg' },
      { image: 'http://alexandro.in/gostops/mussoorie/4.jpg' },
      { image: 'http://alexandro.in/gostops/mussoorie/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Naggar',
    website_Url: '',
    location: ' Near Rorich Art Gallery, Naggar, Himachal Pradesh',
    price_type: 'week',
    starting_price: '2,599',
    show_price: '2,599',
    slug: 'gostops-naggar',
    images: [
      { image: 'http://alexandro.in/gostops/naggar/1.jpg' },
      { image: 'http://alexandro.in/gostops/naggar/2.jpg' },
      { image: 'http://alexandro.in/gostops/naggar/3.jpg' },
      { image: 'http://alexandro.in/gostops/naggar/4.jpg' },
      { image: 'http://alexandro.in/gostops/naggar/5.jpg' },
    ],
  },
  {
    id: '',
    name: 'goSTOPS Delhi',
    website_Url: '',
    location: ' Asaf Ali Rd, Daryaganj, New Delhi',
    price_type: 'week',
    starting_price: '2,799',
    show_price: '2,799',
    slug: 'gostops-delhi',
    images: [
      { image: 'http://alexandro.in/gostops/delhi/1.jpg' },
      { image: 'http://alexandro.in/gostops/delhi/2.jpg' },
      { image: 'http://alexandro.in/gostops/delhi/3.jpg' },
      { image: 'http://alexandro.in/gostops/delhi/4.jpg' },
      { image: 'http://alexandro.in/gostops/delhi/5.jpg' },
    ],
  },
];
